
plugins {
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.3.0'
    id 'org.jetbrains.kotlin.plugin.jpa' version '2.3.0'
    id 'jacoco'
    id 'org.owasp.dependencycheck' version '12.2.0'
}

group = 'com.example'
version = '1.0.0'
java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

repositories { mavenCentral() }

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

    implementation 'org.xerial:sqlite-jdbc:3.47.1.0'
    implementation 'org.hibernate.orm:hibernate-community-dialects:6.6.3.Final'
    implementation "org.jetbrains.kotlin:kotlin-reflect"

    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")

    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    runtimeOnly 'org.flywaydb:flyway-core'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-test-autoconfigure'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.2.1'
    testImplementation 'org.springframework.security:spring-security-test'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

tasks.named('test') { useJUnitPlatform() }

jacoco {
    toolVersion = "0.8.12"
}

tasks.named('test') {
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

def nvdApiKey = System.getenv("NVD_API_KEY")

dependencyCheck {
    data {
        directory = layout.buildDirectory.dir("dependency-check-data").get().asFile.absolutePath
    }
    formats = ["HTML", "XML"]
    failBuildOnCVSS = 7.0
    if (nvdApiKey) {
        nvd {
            apiKey = nvdApiKey
        }
    } else {
        autoUpdate = false
    }
}
